server:
  port: 9092

spring:
  application:
    name: "HOTEl-SERVICE"
  datasource:
    url: jdbc:mysql://localhost:3306/data-hotel
    username: root
    password: Vikas@12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MYSQL8Dialect


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:9090/eureka